#!/usr/bin/env python

# Copyright 2015 Cloudbase Solutions SRL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import devstack

from devstack import run_command

def start_poststack():
    poststack = "/home/ubuntu/devstack/poststack.sh"
    args = [
        poststack,
    ]
    run_command(args)


if __name__ == '__main__':
    ctx = devstack.DevstackContext(username=devstack.DEFAULT_USER)
    ctx.render_ad_credentials()
    ctx.render_nodes()
    start_poststack()

